//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CalifadeLeonEntities : DbContext
    {
        public CalifadeLeonEntities()
            : base("name=CalifadeLeonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Restaurante> Restaurantes { get; set; }
    
        public virtual int AddRestaurant(string nombre, byte[] logo, Nullable<int> capacidad)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var logoParameter = logo != null ?
                new ObjectParameter("Logo", logo) :
                new ObjectParameter("Logo", typeof(byte[]));
    
            var capacidadParameter = capacidad.HasValue ?
                new ObjectParameter("Capacidad", capacidad) :
                new ObjectParameter("Capacidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddRestaurant", nombreParameter, logoParameter, capacidadParameter);
        }
    
        public virtual int DeleteRestaurant(Nullable<int> idRestaurante)
        {
            var idRestauranteParameter = idRestaurante.HasValue ?
                new ObjectParameter("idRestaurante", idRestaurante) :
                new ObjectParameter("idRestaurante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteRestaurant", idRestauranteParameter);
        }
    
        public virtual ObjectResult<GetAllRestaurant_Result> GetAllRestaurant()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllRestaurant_Result>("GetAllRestaurant");
        }
    
        public virtual ObjectResult<GetByIdRestaurante_Result> GetByIdRestaurante(Nullable<int> idRestaurante)
        {
            var idRestauranteParameter = idRestaurante.HasValue ?
                new ObjectParameter("idRestaurante", idRestaurante) :
                new ObjectParameter("idRestaurante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetByIdRestaurante_Result>("GetByIdRestaurante", idRestauranteParameter);
        }
    
        public virtual int UpdateRestaurante(Nullable<int> idRestaurante, string nombre, byte[] logo, Nullable<int> capacidad)
        {
            var idRestauranteParameter = idRestaurante.HasValue ?
                new ObjectParameter("idRestaurante", idRestaurante) :
                new ObjectParameter("idRestaurante", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var logoParameter = logo != null ?
                new ObjectParameter("Logo", logo) :
                new ObjectParameter("Logo", typeof(byte[]));
    
            var capacidadParameter = capacidad.HasValue ?
                new ObjectParameter("Capacidad", capacidad) :
                new ObjectParameter("Capacidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateRestaurante", idRestauranteParameter, nombreParameter, logoParameter, capacidadParameter);
        }
    }
}
